# Cycle Data Munging part 2

#  Merging Dataset

Weather data consist on 600 observations where bikes data is consisting over a hundred thousand of tuples which mean it is not easy to combine.  To achieve this we will, break both weather and bikes data Date columns and applying programming technique to achieve weather value for each bicycle trip.

# Refrences

https://github.com/justmarkham/pandas...
http://pandas.pydata.org/pandas-docs/...
http://pandas.pydata.org/pandas-docs/...
https://github.com/meli-lewis/pycaribbean2016
http://pandas.pydata.org/pandas-docs/stable/api.html#string-handling

# Data Cleaning

In [1]:
# load libraries and set styles, options
import os,csv
import numpy as np
import pandas as pd
import seaborn as sns
import warnings; warnings.simplefilter('ignore')
#from IPython.display import HTML
#HTML('<iframe src=http://www.seattle.gov/documents/departments/sdot/newmobilityprogram/appendixb.pdf width=1000 height=350></iframe>')

In [2]:
%matplotlib inline

2. Read and verify data

In [3]:
# read in a CSV
df1 = pd.read_csv('C:/Users/mrferozi/Desktop/GitHub/Bike/dataset/cycle/weather_clean.csv', index_col=0)
df2 = pd.read_csv('C:/Users/mrferozi/Desktop/GitHub/Bike/dataset/cycle/trip_clean.csv', index_col=0)

In [4]:
df1.dtypes

Date                           object
Max_Temperature_F               int64
Mean_Temperature_F              int64
Min_TemperatureF                int64
Max_Dew_Point_F                 int64
MeanDew_Point_F                 int64
Min_Dewpoint_F                  int64
Max_Humidity                    int64
Mean_Humidity                   int64
Min_Humidity                    int64
Max_Sea_Level_Pressure_In     float64
Mean_Sea_Level_Pressure_In    float64
Min_Sea_Level_Pressure_In     float64
Max_Visibility_Miles            int64
Mean_Visibility_Miles           int64
Min_Visibility_Miles            int64
Max_Wind_Speed_MPH              int64
Mean_Wind_Speed_MPH             int64
Max_Gust_Speed_MPH              int64
Precipitation_In              float64
Events                         object
Mean_Temperature_C              int64
Events_num                      int64
month                           int64
year                            int64
dtype: object

In [5]:
df2.dtypes

trip_id                   int64
starttime                object
stoptime                 object
bikeid                   object
tripduration            float64
from_station_name        object
to_station_name          object
from_station_id          object
to_station_id            object
usertype                 object
gender                   object
birthyear                 int64
Sex_num                 float64
from_station_id_cat      object
from_station_id_num       int64
to_station_id_cat        object
to_station_id_num         int64
Day                      object
Day_cat                  object
Day_num                   int64
sthours                   int64
stphours                  int64
tripduration_minutes    float64
age                       int64
bmonth                    int64
Date                     object
year                      int64
dtype: object

# Data Type Conversion

In [6]:
 # convert 'Time' to datetime format
df1['Date'] = pd.to_datetime(df1.Date)
df2['Date'] = pd.to_datetime(df2.Date)

In [7]:
df1.dtypes

Date                          datetime64[ns]
Max_Temperature_F                      int64
Mean_Temperature_F                     int64
Min_TemperatureF                       int64
Max_Dew_Point_F                        int64
MeanDew_Point_F                        int64
Min_Dewpoint_F                         int64
Max_Humidity                           int64
Mean_Humidity                          int64
Min_Humidity                           int64
Max_Sea_Level_Pressure_In            float64
Mean_Sea_Level_Pressure_In           float64
Min_Sea_Level_Pressure_In            float64
Max_Visibility_Miles                   int64
Mean_Visibility_Miles                  int64
Min_Visibility_Miles                   int64
Max_Wind_Speed_MPH                     int64
Mean_Wind_Speed_MPH                    int64
Max_Gust_Speed_MPH                     int64
Precipitation_In                     float64
Events                                object
Mean_Temperature_C                     int64
Events_num                             int64
month                                  int64
year                                   int64
dtype: object

In [8]:
df2.index

Int64Index([ 20240,  20252,  20255,  20260,  20263,  20265,  20270,  20271,
             20274,  20276,
            ...
            286821, 286822, 286824, 286825, 286840, 286842, 286843, 286844,
            286845, 286847],
           dtype='int64', length=121225)

import pandas as pd
#df2['Temp']=0
Inplace = True
#c = 0
for index, row in df1.iterrows():
    a1 = row.Max_Temperature_F               
    a2 = row.Mean_Temperature_F              
    a3 = row.Min_TemperatureF                
    a4 = row.Max_Dew_Point_F                 
    a5 = row.MeanDew_Point_F                 
    a6 = row.Min_Dewpoint_F                  
    a7 = row.Max_Humidity                    
    a8 = row.Mean_Humidity                   
    a9 = row.Min_Humidity                    
    a10 = row.Max_Sea_Level_Pressure_In     
    a11 = row.Mean_Sea_Level_Pressure_In    
    a12 = row.Min_Sea_Level_Pressure_In     
    a13 = row.Max_Visibility_Miles            
    a14 = row.Mean_Visibility_Miles           
    a15 = row.Min_Visibility_Miles            
    a16 = row.Max_Wind_Speed_MPH              
    a17 = row.Mean_Wind_Speed_MPH             
    a18 = row.Max_Gust_Speed_MPH              
    a19 = row.Precipitation_In              
    a20 = row.Events                         
    a21 = row.Mean_Temperature_C              
    a22 = row.Events_num                      
    a23 = row.month                           
    a24 = row.year
    for index, r in df2.iterrows():
        if (row.Date == r.Date):
            df2.at[index, 'Max_Temperature_F'] = a1              
            df2.at[index, 'Mean_Temperature_F'] = a2              
            df2.at[index, 'Min_TemperatureF'] = a3
            df2.at[index, 'Max_Dew_Point_F'] = a4                
            df2.at[index, 'MeanDew_Point_F'] = a5               
            df2.at[index, 'Min_Dewpoint_F'] = a6                
            df2.at[index, 'Max_Humidity'] = a7             
            df2.at[index, 'Mean_Humidity'] = a8                
            df2.at[index, 'Min_Humidity'] = a9
            df2.at[index, 'Max_Sea_Level_Pressure_In'] = a10
            df2.at[index, 'Mean_Sea_Level_Pressure_In'] = a11
            df2.at[index, 'Min_Sea_Level_Pressure_In'] = a12  
            df2.at[index, 'Max_Visibility_Miles'] = a13           
            df2.at[index, 'Mean_Visibility_Miles'] = a14         
            df2.at[index, 'Min_Visibility_Miles'] = a15          
            df2.at[index, 'Max_Wind_Speed_MPH'] = a16           
            df2.at[index, 'Mean_Wind_Speed_MPH'] = a17           
            df2.at[index, 'Max_Gust_Speed_MPH'] = a18          
            df2.at[index, 'Precipitation_In'] = a20         
            df2.at[index, 'Events'] = a21                      
            df2.at[index, 'Mean_Temperature_C'] = a22          
            df2.at[index, 'Events_num'] = a23                   
            df2.at[index, 'month'] = a24                        
            df2.at[index, 'year'] = a25
            if (row.Date != r.Date):
                break

#df2.groupby('Date').count()
df2['Date'].value_counts()

# Data Merging Process

In [19]:
#create a new data frame
cols = ['Date', 
        'Bike_rented', 
        'Max_Temperature_F',                            
        'Min_TemperatureF',                              
        'Max_Humidity',                                     
        'Min_Humidity',                                   
        'Visibility_Miles',                               
        'Wind_Speed_MPH',                         
        'Precipitation_In',        
        'Events',                        
        'Temperature_C',             
        'Events_num',                     
        'month',                           
        'year']
df3 = pd.DataFrame(columns=cols)

In [20]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 14 columns):
Date                 0 non-null object
Bike_rented          0 non-null object
Max_Temperature_F    0 non-null object
Min_TemperatureF     0 non-null object
Max_Humidity         0 non-null object
Min_Humidity         0 non-null object
Visibility_Miles     0 non-null object
Wind_Speed_MPH       0 non-null object
Precipitation_In     0 non-null object
Events               0 non-null object
Temperature_C        0 non-null object
Events_num           0 non-null object
month                0 non-null object
year                 0 non-null object
dtypes: object(14)
memory usage: 0.0+ bytes

In [21]:
df3.head()

Empty DataFrame
Columns: [Date, Bike_rented, Max_Temperature_F, Min_TemperatureF, Max_Humidity, Min_Humidity, Visibility_Miles, Wind_Speed_MPH, Precipitation_In, Events, Temperature_C, Events_num, month, year]
Index: []

In [22]:
import pandas as pd
Inplace = True
for index, row in df1.iterrows():
    if row.notnull:
        a1 = row.Max_Temperature_F               
        a2 = row.Min_TemperatureF                                
        a3 = row.Max_Humidity                                       
        a4 = row.Min_Humidity                            
        a5 = row.Mean_Visibility_Miles                    
        a6 = row.Mean_Wind_Speed_MPH                           
        a7 = row.Precipitation_In              
        a8 = row.Events                         
        a9 = row.Mean_Temperature_C              
        a10 = row.Events_num                      
        a11 = row.month                           
        a12 = row.year
        a13 = row.Date
        b = 0
        for i, r in df2.iterrows():
            if (row.Date == r.Date):
                b = b + 1
                if not (row.Date == r.Date):
                    break
                    df3.at[index, 'Max_Temperature_F'] = a1                              
                    df3.at[index, 'Min_TemperatureF'] = a2                                  
                    df3.at[index, 'Max_Humidity'] = a3                                        
                    df3.at[index, 'Min_Humidity'] = a4                             
                    df3.at[index, 'Visibility_Miles'] = a5 
                    df3.at[index, 'Wind_Speed_MPH'] = a6                         
                    df3.at[index, 'Precipitation_In'] = a7           
                    df3.at[index, 'Events'] = a8                         
                    df3.at[index, 'Mean_Temperature_C'] = a9              
                    df3.at[index, 'Events_num'] = a10                     
                    df3.at[index, 'month'] = a11                           
                    df3.at[index, 'year'] = a12
                    df3.at[index, 'Date'] = a13
                    df3.at[index, 'Bike_rented'] = b
    print (index,'vlaue of rented bike',b,'Dated',a13)

80 vlaue of rented bike 88 Dated 2015-01-01 00:00:00
81 vlaue of rented bike 92 Dated 2015-02-01 00:00:00
82 vlaue of rented bike 142 Dated 2015-03-01 00:00:00
83 vlaue of rented bike 406 Dated 2015-04-01 00:00:00
84 vlaue of rented bike 265 Dated 2015-05-01 00:00:00
85 vlaue of rented bike 194 Dated 2015-06-01 00:00:00
86 vlaue of rented bike 324 Dated 2015-07-01 00:00:00
87 vlaue of rented bike 128 Dated 2015-08-01 00:00:00
88 vlaue of rented bike 199 Dated 2015-09-01 00:00:00
89 vlaue of rented bike 284 Dated 2015-10-01 00:00:00
90 vlaue of rented bike 69 Dated 2015-11-01 00:00:00
91 vlaue of rented bike 187 Dated 2015-12-01 00:00:00
92 vlaue of rented bike 410 Dated 2015-01-13 00:00:00
93 vlaue of rented bike 388 Dated 2015-01-14 00:00:00
94 vlaue of rented bike 282 Dated 2015-01-15 00:00:00
95 vlaue of rented bike 402 Dated 2015-01-16 00:00:00
96 vlaue of rented bike 110 Dated 2015-01-17 00:00:00
97 vlaue of rented bike 96 Dated 2015-01-18 00:00:00
98 vlaue of rented bike 264 Dated 2015-01-19 00:00:00
99 vlaue of rented bike 484 Dated 2015-01-20 00:00:00
100 vlaue of rented bike 416 Dated 2015-01-21 00:00:00
101 vlaue of rented bike 396 Dated 2015-01-22 00:00:00
102 vlaue of rented bike 310 Dated 2015-01-23 00:00:00
103 vlaue of rented bike 212 Dated 2015-01-24 00:00:00
104 vlaue of rented bike 206 Dated 2015-01-25 00:00:00
105 vlaue of rented bike 378 Dated 2015-01-26 00:00:00
106 vlaue of rented bike 336 Dated 2015-01-27 00:00:00
107 vlaue of rented bike 456 Dated 2015-01-28 00:00:00
108 vlaue of rented bike 462 Dated 2015-01-29 00:00:00
109 vlaue of rented bike 412 Dated 2015-01-30 00:00:00
110 vlaue of rented bike 206 Dated 2015-01-31 00:00:00
111 vlaue of rented bike 180 Dated 2015-01-02 00:00:00
112 vlaue of rented bike 254 Dated 2015-02-02 00:00:00
113 vlaue of rented bike 366 Dated 2015-03-02 00:00:00
114 vlaue of rented bike 402 Dated 2015-04-02 00:00:00
115 vlaue of rented bike 140 Dated 2015-05-02 00:00:00
116 vlaue of rented bike 286 Dated 2015-06-02 00:00:00
117 vlaue of rented bike 327 Dated 2015-07-02 00:00:00
118 vlaue of rented bike 105 Dated 2015-08-02 00:00:00
119 vlaue of rented bike 279 Dated 2015-09-02 00:00:00
120 vlaue of rented bike 258 Dated 2015-10-02 00:00:00
121 vlaue of rented bike 209 Dated 2015-11-02 00:00:00
122 vlaue of rented bike 185 Dated 2015-12-02 00:00:00
123 vlaue of rented bike 450 Dated 2015-02-13 00:00:00
124 vlaue of rented bike 218 Dated 2015-02-14 00:00:00
125 vlaue of rented bike 158 Dated 2015-02-15 00:00:00
126 vlaue of rented bike 210 Dated 2015-02-16 00:00:00
127 vlaue of rented bike 412 Dated 2015-02-17 00:00:00
128 vlaue of rented bike 408 Dated 2015-02-18 00:00:00
129 vlaue of rented bike 342 Dated 2015-02-19 00:00:00
130 vlaue of rented bike 320 Dated 2015-02-20 00:00:00
131 vlaue of rented bike 226 Dated 2015-02-21 00:00:00
132 vlaue of rented bike 156 Dated 2015-02-22 00:00:00
133 vlaue of rented bike 306 Dated 2015-02-23 00:00:00
134 vlaue of rented bike 346 Dated 2015-02-24 00:00:00
135 vlaue of rented bike 286 Dated 2015-02-25 00:00:00
136 vlaue of rented bike 368 Dated 2015-02-26 00:00:00
137 vlaue of rented bike 304 Dated 2015-02-27 00:00:00
138 vlaue of rented bike 176 Dated 2015-02-28 00:00:00
139 vlaue of rented bike 104 Dated 2015-01-03 00:00:00
140 vlaue of rented bike 346 Dated 2015-02-03 00:00:00
141 vlaue of rented bike 414 Dated 2015-03-03 00:00:00
142 vlaue of rented bike 426 Dated 2015-04-03 00:00:00
143 vlaue of rented bike 140 Dated 2015-05-03 00:00:00
144 vlaue of rented bike 278 Dated 2015-06-03 00:00:00
145 vlaue of rented bike 168 Dated 2015-07-03 00:00:00
146 vlaue of rented bike 310 Dated 2015-08-03 00:00:00
147 vlaue of rented bike 307 Dated 2015-09-03 00:00:00
148 vlaue of rented bike 98 Dated 2015-10-03 00:00:00
149 vlaue of rented bike 238 Dated 2015-11-03 00:00:00
150 vlaue of rented bike 185 Dated 2015-12-03 00:00:00
151 vlaue of rented bike 414 Dated 2015-03-13 00:00:00
152 vlaue of rented bike 216 Dated 2015-03-14 00:00:00
153 vlaue of rented bike 40 Dated 2015-03-15 00:00:00
154 vlaue of rented bike 310 Dated 2015-03-16 00:00:00
155 vlaue of rented bike 376 Dated 2015-03-17 00:00:00
156 vlaue of rented bike 468 Dated 2015-03-18 00:00:00
157 vlaue of rented bike 396 Dated 2015-03-19 00:00:00
158 vlaue of rented bike 352 Dated 2015-03-20 00:00:00
159 vlaue of rented bike 202 Dated 2015-03-21 00:00:00
160 vlaue of rented bike 142 Dated 2015-03-22 00:00:00
161 vlaue of rented bike 324 Dated 2015-03-23 00:00:00
162 vlaue of rented bike 364 Dated 2015-03-24 00:00:00
163 vlaue of rented bike 348 Dated 2015-03-25 00:00:00
164 vlaue of rented bike 506 Dated 2015-03-26 00:00:00
165 vlaue of rented bike 454 Dated 2015-03-27 00:00:00
166 vlaue of rented bike 208 Dated 2015-03-28 00:00:00
167 vlaue of rented bike 178 Dated 2015-03-29 00:00:00
168 vlaue of rented bike 446 Dated 2015-03-30 00:00:00
169 vlaue of rented bike 322 Dated 2015-03-31 00:00:00
170 vlaue of rented bike 56 Dated 2015-01-04 00:00:00
171 vlaue of rented bike 316 Dated 2015-02-04 00:00:00
172 vlaue of rented bike 418 Dated 2015-03-04 00:00:00
173 vlaue of rented bike 204 Dated 2015-04-04 00:00:00
174 vlaue of rented bike 258 Dated 2015-05-04 00:00:00
175 vlaue of rented bike 318 Dated 2015-06-04 00:00:00
176 vlaue of rented bike 120 Dated 2015-07-04 00:00:00
177 vlaue of rented bike 308 Dated 2015-08-04 00:00:00
178 vlaue of rented bike 232 Dated 2015-09-04 00:00:00
179 vlaue of rented bike 117 Dated 2015-10-04 00:00:00
180 vlaue of rented bike 233 Dated 2015-11-04 00:00:00
181 vlaue of rented bike 192 Dated 2015-12-04 00:00:00
182 vlaue of rented bike 258 Dated 2015-04-13 00:00:00
183 vlaue of rented bike 464 Dated 2015-04-14 00:00:00
184 vlaue of rented bike 508 Dated 2015-04-15 00:00:00
185 vlaue of rented bike 574 Dated 2015-04-16 00:00:00
186 vlaue of rented bike 391 Dated 2015-04-17 00:00:00
187 vlaue of rented bike 157 Dated 2015-04-18 00:00:00
188 vlaue of rented bike 117 Dated 2015-04-19 00:00:00
189 vlaue of rented bike 279 Dated 2015-04-20 00:00:00
190 vlaue of rented bike 273 Dated 2015-04-21 00:00:00
191 vlaue of rented bike 267 Dated 2015-04-22 00:00:00
192 vlaue of rented bike 216 Dated 2015-04-23 00:00:00
193 vlaue of rented bike 217 Dated 2015-04-24 00:00:00
194 vlaue of rented bike 116 Dated 2015-04-25 00:00:00
195 vlaue of rented bike 125 Dated 2015-04-26 00:00:00
196 vlaue of rented bike 263 Dated 2015-04-27 00:00:00
197 vlaue of rented bike 205 Dated 2015-04-28 00:00:00
198 vlaue of rented bike 236 Dated 2015-04-29 00:00:00
199 vlaue of rented bike 277 Dated 2015-04-30 00:00:00
200 vlaue of rented bike 244 Dated 2015-01-05 00:00:00
201 vlaue of rented bike 252 Dated 2015-02-05 00:00:00
202 vlaue of rented bike 390 Dated 2015-03-05 00:00:00
203 vlaue of rented bike 174 Dated 2015-04-05 00:00:00
204 vlaue of rented bike 218 Dated 2015-05-05 00:00:00
205 vlaue of rented bike 289 Dated 2015-06-05 00:00:00
206 vlaue of rented bike 110 Dated 2015-07-05 00:00:00
207 vlaue of rented bike 330 Dated 2015-08-05 00:00:00
208 vlaue of rented bike 100 Dated 2015-09-05 00:00:00
209 vlaue of rented bike 266 Dated 2015-10-05 00:00:00
210 vlaue of rented bike 222 Dated 2015-11-05 00:00:00
211 vlaue of rented bike 41 Dated 2015-12-05 00:00:00
212 vlaue of rented bike 231 Dated 2015-05-13 00:00:00
213 vlaue of rented bike 286 Dated 2015-05-14 00:00:00
214 vlaue of rented bike 300 Dated 2015-05-15 00:00:00
215 vlaue of rented bike 110 Dated 2015-05-16 00:00:00
216 vlaue of rented bike 117 Dated 2015-05-17 00:00:00
217 vlaue of rented bike 283 Dated 2015-05-18 00:00:00
218 vlaue of rented bike 280 Dated 2015-05-19 00:00:00
219 vlaue of rented bike 314 Dated 2015-05-20 00:00:00
220 vlaue of rented bike 328 Dated 2015-05-21 00:00:00
221 vlaue of rented bike 214 Dated 2015-05-22 00:00:00
222 vlaue of rented bike 129 Dated 2015-05-23 00:00:00
223 vlaue of rented bike 92 Dated 2015-05-24 00:00:00
224 vlaue of rented bike 94 Dated 2015-05-25 00:00:00
225 vlaue of rented bike 271 Dated 2015-05-26 00:00:00
226 vlaue of rented bike 344 Dated 2015-05-27 00:00:00
227 vlaue of rented bike 331 Dated 2015-05-28 00:00:00
228 vlaue of rented bike 317 Dated 2015-05-29 00:00:00
229 vlaue of rented bike 143 Dated 2015-05-30 00:00:00
230 vlaue of rented bike 150 Dated 2015-05-31 00:00:00
231 vlaue of rented bike 408 Dated 2015-01-06 00:00:00
232 vlaue of rented bike 274 Dated 2015-02-06 00:00:00
233 vlaue of rented bike 420 Dated 2015-03-06 00:00:00
234 vlaue of rented bike 436 Dated 2015-04-06 00:00:00
235 vlaue of rented bike 284 Dated 2015-05-06 00:00:00
236 vlaue of rented bike 145 Dated 2015-06-06 00:00:00
237 vlaue of rented bike 312 Dated 2015-07-06 00:00:00
238 vlaue of rented bike 305 Dated 2015-08-06 00:00:00
239 vlaue of rented bike 76 Dated 2015-09-06 00:00:00
240 vlaue of rented bike 266 Dated 2015-10-06 00:00:00
241 vlaue of rented bike 188 Dated 2015-11-06 00:00:00
242 vlaue of rented bike 51 Dated 2015-12-06 00:00:00
243 vlaue of rented bike 179 Dated 2015-06-13 00:00:00
244 vlaue of rented bike 112 Dated 2015-06-14 00:00:00
245 vlaue of rented bike 258 Dated 2015-06-15 00:00:00
246 vlaue of rented bike 305 Dated 2015-06-16 00:00:00
247 vlaue of rented bike 307 Dated 2015-06-17 00:00:00
248 vlaue of rented bike 297 Dated 2015-06-18 00:00:00
249 vlaue of rented bike 248 Dated 2015-06-19 00:00:00
250 vlaue of rented bike 127 Dated 2015-06-20 00:00:00
251 vlaue of rented bike 100 Dated 2015-06-21 00:00:00
252 vlaue of rented bike 254 Dated 2015-06-22 00:00:00
253 vlaue of rented bike 307 Dated 2015-06-23 00:00:00
254 vlaue of rented bike 310 Dated 2015-06-24 00:00:00
255 vlaue of rented bike 320 Dated 2015-06-25 00:00:00
256 vlaue of rented bike 286 Dated 2015-06-26 00:00:00
257 vlaue of rented bike 129 Dated 2015-06-27 00:00:00
258 vlaue of rented bike 125 Dated 2015-06-28 00:00:00
259 vlaue of rented bike 318 Dated 2015-06-29 00:00:00
260 vlaue of rented bike 334 Dated 2015-06-30 00:00:00
261 vlaue of rented bike 408 Dated 2015-01-07 00:00:00
262 vlaue of rented bike 124 Dated 2015-02-07 00:00:00
263 vlaue of rented bike 246 Dated 2015-03-07 00:00:00
264 vlaue of rented bike 494 Dated 2015-04-07 00:00:00
265 vlaue of rented bike 338 Dated 2015-05-07 00:00:00
266 vlaue of rented bike 121 Dated 2015-06-07 00:00:00
267 vlaue of rented bike 314 Dated 2015-07-07 00:00:00
268 vlaue of rented bike 308 Dated 2015-08-07 00:00:00
269 vlaue of rented bike 97 Dated 2015-09-07 00:00:00
270 vlaue of rented bike 172 Dated 2015-10-07 00:00:00
271 vlaue of rented bike 32 Dated 2015-11-07 00:00:00
272 vlaue of rented bike 129 Dated 2015-12-07 00:00:00
273 vlaue of rented bike 314 Dated 2015-07-13 00:00:00
274 vlaue of rented bike 350 Dated 2015-07-14 00:00:00
275 vlaue of rented bike 328 Dated 2015-07-15 00:00:00
276 vlaue of rented bike 347 Dated 2015-07-16 00:00:00
277 vlaue of rented bike 283 Dated 2015-07-17 00:00:00
278 vlaue of rented bike 181 Dated 2015-07-18 00:00:00
279 vlaue of rented bike 81 Dated 2015-07-19 00:00:00
280 vlaue of rented bike 291 Dated 2015-07-20 00:00:00
281 vlaue of rented bike 309 Dated 2015-07-21 00:00:00
282 vlaue of rented bike 320 Dated 2015-07-22 00:00:00
283 vlaue of rented bike 328 Dated 2015-07-23 00:00:00
284 vlaue of rented bike 268 Dated 2015-07-24 00:00:00
285 vlaue of rented bike 123 Dated 2015-07-25 00:00:00
286 vlaue of rented bike 103 Dated 2015-07-26 00:00:00
287 vlaue of rented bike 275 Dated 2015-07-27 00:00:00
288 vlaue of rented bike 327 Dated 2015-07-28 00:00:00
289 vlaue of rented bike 348 Dated 2015-07-29 00:00:00
290 vlaue of rented bike 320 Dated 2015-07-30 00:00:00
291 vlaue of rented bike 283 Dated 2015-07-31 00:00:00
292 vlaue of rented bike 414 Dated 2015-01-08 00:00:00
293 vlaue of rented bike 130 Dated 2015-02-08 00:00:00
294 vlaue of rented bike 218 Dated 2015-03-08 00:00:00
295 vlaue of rented bike 488 Dated 2015-04-08 00:00:00
296 vlaue of rented bike 353 Dated 2015-05-08 00:00:00
297 vlaue of rented bike 303 Dated 2015-06-08 00:00:00
298 vlaue of rented bike 356 Dated 2015-07-08 00:00:00
299 vlaue of rented bike 158 Dated 2015-08-08 00:00:00
300 vlaue of rented bike 267 Dated 2015-09-08 00:00:00
301 vlaue of rented bike 289 Dated 2015-10-08 00:00:00
302 vlaue of rented bike 53 Dated 2015-11-08 00:00:00
303 vlaue of rented bike 118 Dated 2015-12-08 00:00:00
304 vlaue of rented bike 296 Dated 2015-08-13 00:00:00
305 vlaue of rented bike 195 Dated 2015-08-14 00:00:00
306 vlaue of rented bike 140 Dated 2015-08-15 00:00:00
307 vlaue of rented bike 135 Dated 2015-08-16 00:00:00
308 vlaue of rented bike 275 Dated 2015-08-17 00:00:00
309 vlaue of rented bike 318 Dated 2015-08-18 00:00:00
310 vlaue of rented bike 330 Dated 2015-08-19 00:00:00
311 vlaue of rented bike 280 Dated 2015-08-20 00:00:00
312 vlaue of rented bike 306 Dated 2015-08-21 00:00:00
313 vlaue of rented bike 134 Dated 2015-08-22 00:00:00
314 vlaue of rented bike 115 Dated 2015-08-23 00:00:00
315 vlaue of rented bike 276 Dated 2015-08-24 00:00:00
316 vlaue of rented bike 282 Dated 2015-08-25 00:00:00
317 vlaue of rented bike 285 Dated 2015-08-26 00:00:00
318 vlaue of rented bike 285 Dated 2015-08-27 00:00:00
319 vlaue of rented bike 246 Dated 2015-08-28 00:00:00
320 vlaue of rented bike 79 Dated 2015-08-29 00:00:00
321 vlaue of rented bike 127 Dated 2015-08-30 00:00:00
322 vlaue of rented bike 229 Dated 2015-08-31 00:00:00
323 vlaue of rented bike 384 Dated 2015-01-09 00:00:00
324 vlaue of rented bike 334 Dated 2015-02-09 00:00:00
325 vlaue of rented bike 384 Dated 2015-03-09 00:00:00
326 vlaue of rented bike 498 Dated 2015-04-09 00:00:00
327 vlaue of rented bike 190 Dated 2015-05-09 00:00:00
328 vlaue of rented bike 308 Dated 2015-06-09 00:00:00
329 vlaue of rented bike 311 Dated 2015-07-09 00:00:00
330 vlaue of rented bike 122 Dated 2015-08-09 00:00:00
331 vlaue of rented bike 323 Dated 2015-09-09 00:00:00
332 vlaue of rented bike 247 Dated 2015-10-09 00:00:00
333 vlaue of rented bike 201 Dated 2015-11-09 00:00:00
334 vlaue of rented bike 173 Dated 2015-12-09 00:00:00
335 vlaue of rented bike 73 Dated 2015-09-13 00:00:00
336 vlaue of rented bike 233 Dated 2015-09-14 00:00:00
337 vlaue of rented bike 272 Dated 2015-09-15 00:00:00
338 vlaue of rented bike 288 Dated 2015-09-16 00:00:00
339 vlaue of rented bike 210 Dated 2015-09-17 00:00:00
340 vlaue of rented bike 211 Dated 2015-09-18 00:00:00
341 vlaue of rented bike 97 Dated 2015-09-19 00:00:00
342 vlaue of rented bike 81 Dated 2015-09-20 00:00:00
343 vlaue of rented bike 250 Dated 2015-09-21 00:00:00
344 vlaue of rented bike 312 Dated 2015-09-22 00:00:00
345 vlaue of rented bike 298 Dated 2015-09-23 00:00:00
346 vlaue of rented bike 310 Dated 2015-09-24 00:00:00
347 vlaue of rented bike 225 Dated 2015-09-25 00:00:00
348 vlaue of rented bike 114 Dated 2015-09-26 00:00:00
349 vlaue of rented bike 75 Dated 2015-09-27 00:00:00
350 vlaue of rented bike 261 Dated 2015-09-28 00:00:00
351 vlaue of rented bike 297 Dated 2015-09-29 00:00:00
352 vlaue of rented bike 264 Dated 2015-09-30 00:00:00
353 vlaue of rented bike 152 Dated 2015-01-10 00:00:00
354 vlaue of rented bike 426 Dated 2015-02-10 00:00:00
355 vlaue of rented bike 494 Dated 2015-03-10 00:00:00
356 vlaue of rented bike 388 Dated 2015-04-10 00:00:00
357 vlaue of rented bike 130 Dated 2015-05-10 00:00:00
358 vlaue of rented bike 304 Dated 2015-06-10 00:00:00
359 vlaue of rented bike 300 Dated 2015-07-10 00:00:00
360 vlaue of rented bike 261 Dated 2015-08-10 00:00:00
361 vlaue of rented bike 285 Dated 2015-09-10 00:00:00
362 vlaue of rented bike 60 Dated 2015-10-10 00:00:00
363 vlaue of rented bike 232 Dated 2015-11-10 00:00:00
364 vlaue of rented bike 156 Dated 2015-12-10 00:00:00
365 vlaue of rented bike 276 Dated 2015-10-13 00:00:00
366 vlaue of rented bike 238 Dated 2015-10-14 00:00:00
367 vlaue of rented bike 259 Dated 2015-10-15 00:00:00
368 vlaue of rented bike 287 Dated 2015-10-16 00:00:00
369 vlaue of rented bike 91 Dated 2015-10-17 00:00:00
370 vlaue of rented bike 36 Dated 2015-10-18 00:00:00
371 vlaue of rented bike 242 Dated 2015-10-19 00:00:00
372 vlaue of rented bike 271 Dated 2015-10-20 00:00:00
373 vlaue of rented bike 269 Dated 2015-10-21 00:00:00
374 vlaue of rented bike 253 Dated 2015-10-22 00:00:00
375 vlaue of rented bike 237 Dated 2015-10-23 00:00:00
376 vlaue of rented bike 97 Dated 2015-10-24 00:00:00
377 vlaue of rented bike 84 Dated 2015-10-25 00:00:00
378 vlaue of rented bike 183 Dated 2015-10-26 00:00:00
379 vlaue of rented bike 258 Dated 2015-10-27 00:00:00
380 vlaue of rented bike 236 Dated 2015-10-28 00:00:00
381 vlaue of rented bike 236 Dated 2015-10-29 00:00:00
382 vlaue of rented bike 199 Dated 2015-10-30 00:00:00
383 vlaue of rented bike 44 Dated 2015-10-31 00:00:00
384 vlaue of rented bike 110 Dated 2015-01-11 00:00:00
385 vlaue of rented bike 420 Dated 2015-02-11 00:00:00
386 vlaue of rented bike 358 Dated 2015-03-11 00:00:00
387 vlaue of rented bike 150 Dated 2015-04-11 00:00:00
388 vlaue of rented bike 282 Dated 2015-05-11 00:00:00
389 vlaue of rented bike 308 Dated 2015-06-11 00:00:00
390 vlaue of rented bike 131 Dated 2015-07-11 00:00:00
391 vlaue of rented bike 320 Dated 2015-08-11 00:00:00
392 vlaue of rented bike 288 Dated 2015-09-11 00:00:00
393 vlaue of rented bike 93 Dated 2015-10-11 00:00:00
394 vlaue of rented bike 189 Dated 2015-11-11 00:00:00
395 vlaue of rented bike 175 Dated 2015-12-11 00:00:00
396 vlaue of rented bike 157 Dated 2015-11-13 00:00:00
397 vlaue of rented bike 26 Dated 2015-11-14 00:00:00
398 vlaue of rented bike 65 Dated 2015-11-15 00:00:00
399 vlaue of rented bike 156 Dated 2015-11-16 00:00:00
400 vlaue of rented bike 146 Dated 2015-11-17 00:00:00
401 vlaue of rented bike 219 Dated 2015-11-18 00:00:00
402 vlaue of rented bike 212 Dated 2015-11-19 00:00:00
403 vlaue of rented bike 193 Dated 2015-11-20 00:00:00
404 vlaue of rented bike 64 Dated 2015-11-21 00:00:00
405 vlaue of rented bike 73 Dated 2015-11-22 00:00:00
406 vlaue of rented bike 158 Dated 2015-11-23 00:00:00
407 vlaue of rented bike 149 Dated 2015-11-24 00:00:00
408 vlaue of rented bike 151 Dated 2015-11-25 00:00:00
409 vlaue of rented bike 20 Dated 2015-11-26 00:00:00
410 vlaue of rented bike 50 Dated 2015-11-27 00:00:00
411 vlaue of rented bike 54 Dated 2015-11-28 00:00:00
412 vlaue of rented bike 50 Dated 2015-11-29 00:00:00
413 vlaue of rented bike 146 Dated 2015-11-30 00:00:00
414 vlaue of rented bike 396 Dated 2015-01-12 00:00:00
415 vlaue of rented bike 448 Dated 2015-02-12 00:00:00
416 vlaue of rented bike 484 Dated 2015-03-12 00:00:00
417 vlaue of rented bike 162 Dated 2015-04-12 00:00:00
418 vlaue of rented bike 279 Dated 2015-05-12 00:00:00
419 vlaue of rented bike 275 Dated 2015-06-12 00:00:00
420 vlaue of rented bike 123 Dated 2015-07-12 00:00:00
421 vlaue of rented bike 307 Dated 2015-08-12 00:00:00
422 vlaue of rented bike 116 Dated 2015-09-12 00:00:00
423 vlaue of rented bike 249 Dated 2015-10-12 00:00:00
424 vlaue of rented bike 172 Dated 2015-11-12 00:00:00
425 vlaue of rented bike 37 Dated 2015-12-12 00:00:00
426 vlaue of rented bike 41 Dated 2015-12-13 00:00:00
427 vlaue of rented bike 185 Dated 2015-12-14 00:00:00
428 vlaue of rented bike 175 Dated 2015-12-15 00:00:00
429 vlaue of rented bike 165 Dated 2015-12-16 00:00:00
430 vlaue of rented bike 119 Dated 2015-12-17 00:00:00
431 vlaue of rented bike 171 Dated 2015-12-18 00:00:00
432 vlaue of rented bike 65 Dated 2015-12-19 00:00:00
433 vlaue of rented bike 51 Dated 2015-12-20 00:00:00
434 vlaue of rented bike 99 Dated 2015-12-21 00:00:00
435 vlaue of rented bike 126 Dated 2015-12-22 00:00:00
436 vlaue of rented bike 89 Dated 2015-12-23 00:00:00
437 vlaue of rented bike 66 Dated 2015-12-24 00:00:00
438 vlaue of rented bike 14 Dated 2015-12-25 00:00:00
439 vlaue of rented bike 27 Dated 2015-12-26 00:00:00
440 vlaue of rented bike 13 Dated 2015-12-27 00:00:00
441 vlaue of rented bike 94 Dated 2015-12-28 00:00:00
442 vlaue of rented bike 108 Dated 2015-12-29 00:00:00
443 vlaue of rented bike 89 Dated 2015-12-30 00:00:00

In [24]:
df3

Empty DataFrame
Columns: [Date, Bike_rented, Max_Temperature_F, Min_TemperatureF, Max_Humidity, Min_Humidity, Visibility_Miles, Wind_Speed_MPH, Precipitation_In, Events, Temperature_C, Events_num, month, year]
Index: []

# Saving Data

In [ ]:
df3.to_csv('C:\\Users\\mrferozi\\Desktop\\GitHub\\Bike\\dataset\\cycle\\trip_weather2.csv')